### ISSUE TITLE
iOS: duplicate symbol error on build

### ISSUE THREAD

**Issue by alexaround25** [MattFoley/react-native-paypal#29]
I have followed all the steps, I have changed import in MFLReactNativePayPal.m from:
`
#import "RCTBridge.h"
#import "RCTConvert.h"
`
to
`
#import "React/RCTBridge.h"
#import "React/RCTConvert.h"
`

in order to work with React Native 0.54, but when I try to build the app I get the following type of errors:

```
duplicate symbol _OBJC_IVAR_$_PPRiskDeviceData._adId in:
    /Users/alexandrumic/Documents/Alex/Projects/Culticks_App/ios/Pods/PayPal-iOS-SDK/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/alexandrumic/Library/Developer/Xcode/DerivedData/Culticks_App-fwbfzjapamdvldanrafbzvhbqces/Build/Products/Debug-iphoneos/libMFLReactNativePayPal.a(PPRiskDeviceData.o)
duplicate symbol _OBJC_IVAR_$_PPRiskDeviceData._currentLocation in:
    /Users/alexandrumic/Documents/Alex/Projects/Culticks_App/ios/Pods/PayPal-iOS-SDK/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/alexandrumic/Library/Developer/Xcode/DerivedData/Culticks_App-fwbfzjapamdvldanrafbzvhbqces/Build/Products/Debug-iphoneos/libMFLReactNativePayPal.a(PPRiskDeviceData.o)
duplicate symbol _OBJC_METACLASS_$_PPRiskDeviceData in:
    /Users/alexandrumic/Documents/Alex/Projects/Culticks_App/ios/Pods/PayPal-iOS-SDK/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/alexandrumic/Library/Developer/Xcode/DerivedData/Culticks_App-fwbfzjapamdvldanrafbzvhbqces/Build/Products/Debug-iphoneos/libMFLReactNativePayPal.a(PPRiskDeviceData.o)
ld: 1253 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Can you please tell us if the library is still maintained and working?

Thank you!
